### ISSUE TITLE
Exercise 2.14.6

### ISSUE THREAD

**Issue by Sadye** [ndvanforeest/queueing_book#4]
Volgens mij klopt de solution (of de vraag) niet. Als we bijvoorbeeld een D/D/1 queue nemen waarbij arrivals iedere op t=0,2,4... etc zijn, en service time altijd 1, dan geldt dat 

![](http://latex2png.com/output//latex_bf03de08a0929aae9e937198c8470120.png)

Ander tegenvoorbeeld is wanneer we een G/G/1/1 queue hebben. 

(Het gaat dus om deze redenatie: "the fraction of time the queue length is zero given
that the server is busy, is smaller than the fraction of time the queue length is zero", die niet in alle situaties waar is.)

**Comment by ndvanforeest** [comment]
Ik zal het even bekijken vanavond of morgen. Bedankt in ieder geval.

**Comment by ndvanforeest** [comment]
Hoi,

Ik heb besloten de vraag te verwijderen. Wat ik wou illustreren vergt meer
uitleg dan wat er staat, en of dat dan duidelijker wordt, weet ik niet.

Voor jouw voorbeeld met de D/D/1 queue,  geldt dat \E L \given B  = 1.
Echter \E L_Q =1/2

Mocht je meer puntjes tegen komen, laat het dan weten.

**Comment by ndvanforeest** [comment]
see above
