### ISSUE TITLE
Possible error in solution Exercise 1.11.5

### ISSUE THREAD

**Issue by BobbyBobster** [ndvanforeest/queueing_book#9]
In the third step of this derivation the upper bound for the summation changes from 'c' to 'c-1' without any clear reason or effect. I expect this to be an error, a back-of-the-envelope calculation also showed the change in upper bound to be wrong.
The last step follows with this (supposed) error, and hence would be wrong too.

If I am not mistaken the final answer should be 'lambda divided by mu'.

https://github.com/ndvanforeest/queueing_book/blob/ec7c819267c39a5655382d8142343096f9dadd17/tex_files/mnmn1.tex#L254-L260

**Comment by ndvanforeest** [comment]
Please check the updated version.
